#!/usr/bin/bash

message_file=$AISH_SESSION/messages.txt

make_message $message_file "これから提供するログと変更点を読んで下さい"
#send_request $message_file
echo ----
echo "# log"
git --no-pager log -n 5
echo ----
echo "# diff"
git --no-pager diff --cached
echo ----
codeblock_count=$(wc -l $AISH_SESSION/codeblock_* | awk '{print $1}')
make_message $message_file "上記のdiffから意図を抽出しコミットメッセージを書いて下さい"
send_request $message_file
if [ $codeblock_count -gt 0 ];
then
  commit_message_file=$(ls -t $AISH_SESSION/codeblock_* | tail -n 1)
  echo "commit message: $commit_message_file"
  git commit --template=$commit_message_file
fi
