#!/bin/bash

session=$(mktemp)
rm $session
mkdir $session
export AISH_SESSION="$session"
export AISH_LOGFILE="$session/script.log"
script -O $AISH_LOGFILE
#script -f -c 'bash --rcfile <(echo ". $HOME/.aish/aishrc; exec bash")' -O $AISH_LOGFILE
echo "end"
#rm -rf $session
