#!/usr/bin/bash

message_file=$AISH_SESSION/messages.txt
system_instruction=$(cat $AISH_HOME/task.d/op/system_instruction.txt | jq -Rs '.')
make_message $message_file "$*" "$system_instruction"
send_request $message_file

