#!/usr/bin/bash

dot_aish=$(detail.aish_find_dot_aish)

while getopts "s" opt; do
    case $opt in
        s) with_sources="true" ;;
        *)  ;;
    esac
done
shift $((OPTIND - 1))

system_instruction=$(detail.aish_puts_as_markdown $AISH_HOME/task.d/review/???_*.md)

# Check if sources should be included
if [ "$with_sources" == "true" ]; then
    if [ -f "$dot_aish/task.d/review/sources" ]; then
        sources=$(cat "$dot_aish/task.d/review/sources" 2> /dev/null)
        detail.aish_puts_as_markdown $sources
    fi
fi
git --no-pager diff --cached

query -s "$system_instruction" "$@"