#!/bin/bash

#set -x


if [ -z "$AISH_HOME" ]; then
  export AISH_HOME="$HOME/.aish"
fi

if [ -e "$HOME/.apikey" ]; then
  . $HOME/.apikey
fi

. $AISH_HOME/functions

bind -x '"\C-l": aish_clear'

export PS1_ORG=$PS1
export PROMPT_COMMAND='PS1="(aish:$(detail.aish_calc_message_size))$PS1_ORG"'
export AISH_PID=$PPID
export AISH_MAX_SEND_MESSAGE=5

