#!/bin/bash

function aish_flush_script_log
{
  kill -USR1 $AISH_PID
}
function aish_truncate_script_log
{
  truncate -s 0 $AISH_LOGFILE
}
function aish_rollout
{
  aish_flush_script_log
  sed -r 's/\x1b\[[0-9;]*[a-zA-Z]//g' $AISH_LOGFILE | col -b > $AISH_SESSION/part_$(date +%Y%m%d%H%M%S)_user.txt
  aish_truncate_script_log
}
function aish_clear
{
  rm -f $AISH_SESSION/part_*
  aish_flush_script_log
  aish_truncate_script_log
  clear
}
function aish_calc_message_size
{
  aish_flush_script_log
  sed -r 's/\x1b\[[0-9;]*[a-zA-Z]//g' $AISH_LOGFILE | col -b > $AISH_SESSION/tmp_user.txt
  env LANG=C du --apparent-size -ch $(find $AISH_SESSION -name 'part_*') $AISH_SESSION/tmp_user.txt | grep 'total$' | sed -e 's/[ \t]\+total$//'
}
function aish_pickup_codeblock
{
  start_marker='```'
  end_marker='```'

  file_num=1

  rm -f $AISH_SESSION/code_block_*

  while IFS= read -r line; do
    if [[ "$line" =~ ^\ *"$start_marker"* ]]; then
      file_name="$AISH_SESSION/code_block_$file_num.txt"
      #exec >> "$file_name"

      while IFS= read -r code_line; do
        if [[ "$code_line" =~ ^\ *"$end_marker" ]]; then
          break
        fi
        echo "$code_line" >> "$file_name"
      done

      file_num=$((file_num + 1))
    fi
  done
}
