#!/bin/bash

function gptsh_flush_script_log
{
  kill -USR1 $GPTSH_PID
}
function gptsh_truncate_script_log
{
  truncate -s 0 $GPTSH_LOGFILE
}
function gptsh_rollout
{
  gptsh_flush_script_log
  cp $GPTSH_LOGFILE $GPTSH_SESSION/part_$(date +%Y%m%d%H%M%S)_user.txt
  gptsh_truncate_script_log
}
function gptsh_clear
{
  clear
  rm -f $GPTSH_SESSION/part_*
  gptsh_flush_script_log
  gptsh_truncate_script_log
}
