#!/usr/bin/bash

message_file=$AISH_SESSION/messages.txt
system_instruction=$(cat $AISH_HOME/task.d/fixit/system_instruction.md | jq -Rs '.')

make_message $message_file "$*" "$system_instruction"
send_request $message_file

